export type DemoBin = {
  id: string;
  icon: string;
  name: string;
  count: number;
  kind: "manual" | "smart";
  rule?: string;
};

export type DemoClip = {
  id: string;
  app: string;
  icon: string;
  text: string;
  detail?: string;
  meta: string;
  tone: "amber" | "blue" | "mint" | "rose" | "violet";
  clipType: "Text" | "File" | "Image";
  contentType: string;
  bin: string;
  note?: string;
  moment: string;
};

export const demoLibraryTotal = 684;

export const demoBins: DemoBin[] = [
  { id: "commerce", icon: "🛒", name: "Questionable Commerce", count: 48, kind: "smart", rule: "Links from Amazon and regrettable storefronts" },
  { id: "omarchy", icon: "▰", name: "Omarchy Rabbit Hole", count: 31, kind: "smart", rule: "Source is Browser · Text contains Omarchy" },
  { id: "dhh", icon: "🏎", name: "DHH Fan Club HQ", count: 17, kind: "manual" },
  { id: "lint", icon: "🧶", name: "Pocket Lint Thesis", count: 22, kind: "manual" },
  { id: "follicles", icon: "🧪", name: "Follicular R&D", count: 9, kind: "smart", rule: "Content Type is Research · Text contains hair" },
  { id: "lucasarts", icon: "🏴‍☠️", name: "LucasArts Archaeology", count: 64, kind: "smart", rule: "Text contains pirate, mansion, hamster, or SCUMM" },
  { id: "recipes", icon: "🥘", name: "Mildly Cursed Recipes", count: 26, kind: "smart", rule: "Content Type is Recipe · Regret score above 80%" },
  { id: "remember", icon: "🧠", name: "Things I’ll Definitely Remember", count: 113, kind: "manual" },
  { id: "vollebak", icon: "🧥", name: "Objects Built to Outlive Me", count: 19, kind: "smart", rule: "Text contains Vollebak, copper, ceramic, or apocalypse" },
  { id: "metroid", icon: "◉", name: "Chozo Personnel Files", count: 42, kind: "smart", rule: "Text contains Samus, Metroid, Zebes, Tallon, or morph ball" },
  { id: "wordpress", icon: "W", name: "CMS Archaeology", count: 76, kind: "smart", rule: "Source is WordPress · Includes BuddyPress and bbPress" },
  { id: "technics", icon: "◍", name: "One More Turntable", count: 12, kind: "manual" },
  { id: "factorio", icon: "⚙", name: "The Factory Must Grow", count: 58, kind: "smart", rule: "Text contains inserter, belt, biter, throughput, or copper cable" },
];

const featuredDemoClips: DemoClip[] = [
  {
    id: "amazon-banana-phone",
    app: "Safari",
    icon: "↗",
    text: "amazon.com/s?k=banana+phone+bluetooth+handset",
    detail: "A Bluetooth banana handset. Potassium not included.",
    meta: "just now",
    tone: "blue",
    clipType: "Text",
    contentType: "URL",
    bin: "commerce",
    note: "Expense category: essential telecommunications fruit.",
    moment: "SMART BIN MATCHED",
  },
  {
    id: "pocket-lint-title",
    app: "Notes",
    icon: "Aa",
    text: "What Your Pocket Lint Says About You",
    detail: "A 4,000-word inquiry into fiber, identity, and the tiny receipts we carry inside ourselves.",
    meta: "43 sec",
    tone: "amber",
    clipType: "Text",
    contentType: "Draft",
    bin: "lint",
    note: "Open with the dryer as unreliable narrator.",
    moment: "NOTE ADDED",
  },
  {
    id: "omarchy-manual",
    app: "Firefox",
    icon: "↗",
    text: "https://omarchy.org/manual/",
    detail: "Unified Clipboard & History is chapter eight. This is either research or industrial espionage.",
    meta: "2 min",
    tone: "violet",
    clipType: "Text",
    contentType: "URL",
    bin: "omarchy",
    note: "Read after changing the theme for the sixth time.",
    moment: "CLASSIFIED LOCALLY",
  },
  {
    id: "toe-hair-formula",
    app: "Numbers",
    icon: "ƒx",
    text: "Toe-hair growth formula v7: rosemary oil + optimism ÷ socks",
    detail: "Confidence interval: sandal season.",
    meta: "4 min",
    tone: "mint",
    clipType: "Text",
    contentType: "Research",
    bin: "follicles",
    note: "Peer review declined to participate.",
    moment: "EXTRACTOR FINISHED",
  },
  {
    id: "insult-swordfighting",
    app: "ScummVM",
    icon: "☠",
    text: "You fight like a dairy farmer!",
    detail: "How appropriate. You fight like a cow.",
    meta: "6 min",
    tone: "rose",
    clipType: "Text",
    contentType: "Quote",
    bin: "lucasarts",
    note: "Approved for hostile code review.",
    moment: "PINNED FOR COMBAT",
  },
  {
    id: "dhh-club",
    app: "Messages",
    icon: "…",
    text: "DHH Fan Club meeting moved to the left lane of the Nürburgring",
    detail: "Agenda: Ruby, racing, Linux, and why the meeting has no agenda.",
    meta: "9 min",
    tone: "blue",
    clipType: "Text",
    contentType: "Event",
    bin: "dhh",
    note: "Bring a mechanical keyboard and a strongly held default.",
    moment: "ADDED TO BIN",
  },
  {
    id: "rubber-chicken",
    app: "Safari",
    icon: "↗",
    text: "amazon.com/s?k=rubber+chicken+with+a+pulley+in+the+middle",
    detail: "For crossing ravines and explaining inventory systems.",
    meta: "12 min",
    tone: "blue",
    clipType: "Text",
    contentType: "URL",
    bin: "commerce",
    note: "Do not combine with cable. Or do. I am not the lookout.",
    moment: "DUPLICATE MERGED",
  },
  {
    id: "hamster-warning",
    app: "TextEdit",
    icon: "T",
    text: "WARNING: DO NOT MICROWAVE HAMSTER",
    detail: "The mansion safety committee would like to stress that this rule is not retroactive.",
    meta: "18 min",
    tone: "rose",
    clipType: "Text",
    contentType: "Warning",
    bin: "lucasarts",
    note: "Edna says this signage ruins the ambiance.",
    moment: "PROTECTED AUTOMATICALLY",
  },
  {
    id: "omarchy-theme",
    app: "Terminal",
    icon: ">_",
    text: "omarchy-theme-set tokyo-night",
    detail: "Changed the entire operating system aesthetic instead of answering one email.",
    meta: "24 min",
    tone: "mint",
    clipType: "Text",
    contentType: "Command",
    bin: "omarchy",
    note: "Productivity increased by an unmeasurable but beautiful amount.",
    moment: "COPIED FROM CLI",
  },
  {
    id: "lint-outline",
    app: "Obsidian",
    icon: "◇",
    text: "I. The archaeology of the pocket\nII. Crumb or fiber?\nIII. Toward a unified lint theory",
    detail: "Working outline, increasingly difficult to defend.",
    meta: "31 min",
    tone: "violet",
    clipType: "Text",
    contentType: "Outline",
    bin: "lint",
    note: "Needs a section on denim as habitat.",
    moment: "REVISION SAVED",
  },
  {
    id: "pirate-job",
    app: "Mail",
    icon: "@",
    text: "RE: Three-headed monkey sighting — references attached",
    detail: "Applicant demonstrates excellent distraction instincts and extensive Caribbean travel.",
    meta: "38 min",
    tone: "amber",
    clipType: "Text",
    contentType: "Email",
    bin: "lucasarts",
    note: "Forward to the lookout immediately.",
    moment: "QUEUE POSITION 1",
  },
  {
    id: "toe-hair-chart",
    app: "Preview",
    icon: "▧",
    text: "follicular-velocity-final-FINAL-3.pdf",
    detail: "Figure 2 suggests the left pinky toe is an unexplained outlier.",
    meta: "46 min",
    tone: "rose",
    clipType: "File",
    contentType: "PDF",
    bin: "follicles",
    note: "OCR found 87 uses of ‘promising.’ Suspicious.",
    moment: "OCR MADE SEARCHABLE",
  },
  {
    id: "amazon-finger-hands",
    app: "Arc",
    icon: "↗",
    text: "amazon.com/s?k=tiny+hands+for+fingers",
    detail: "Finally: hands with the correct hand-to-hand ratio.",
    meta: "1 hr",
    tone: "blue",
    clipType: "Text",
    contentType: "URL",
    bin: "commerce",
    note: "Buy ten. Wear all ten. Become management.",
    moment: "SMART BIN MATCHED",
  },
  {
    id: "scumm-spec",
    app: "Xcode",
    icon: "{ }",
    text: "const verb = pickUp(useWith(open(close(give))))",
    detail: "A modern interface proposal with only nine verbs and one extremely judgmental cursor.",
    meta: "1 hr",
    tone: "mint",
    clipType: "Text",
    contentType: "Code",
    bin: "lucasarts",
    note: "Ship behind the ‘ask about LOOM’ flag.",
    moment: "TRANSFORM APPLIED",
  },
  {
    id: "dhh-sticker",
    app: "Finder",
    icon: "◫",
    text: "ship-it-like-it-is-2004-sticker@2x.png",
    detail: "Transparent background. Opaque opinion.",
    meta: "2 hr",
    tone: "violet",
    clipType: "Image",
    contentType: "PNG",
    bin: "dhh",
    note: "Candidate fan club crest, pending trademark sanity.",
    moment: "IMAGE PREVIEW READY",
  },
  {
    id: "lint-conclusion",
    app: "Pages",
    icon: "¶",
    text: "In conclusion, the lint was inside us all along.",
    detail: "A brave thesis weakened only by evidence, methodology, and the conclusion.",
    meta: "3 hr",
    tone: "amber",
    clipType: "Text",
    contentType: "Draft",
    bin: "lint",
    note: "Too powerful? Ask the pocket ethics board.",
    moment: "PASTE-BY-ID READY",
  },
  {
    id: "amazon-horse-mask",
    app: "Safari",
    icon: "↗",
    text: "amazon.com/s?k=horse+head+mask+business+casual",
    detail: "For hybrid meetings where the camera-on policy has become adversarial.",
    meta: "4 hr",
    tone: "blue",
    clipType: "Text",
    contentType: "URL",
    bin: "commerce",
    note: "Pairs with slacks. Does not pair with trust.",
    moment: "PURCHASE INTENT DETECTED",
  },
  {
    id: "omarchy-clipboard-chapter",
    app: "Safari",
    icon: "↗",
    text: "Omarchy Manual → Unified Clipboard & History",
    detail: "Competitive research into what happens when your clipboard develops a tiling window manager.",
    meta: "5 hr",
    tone: "violet",
    clipType: "Text",
    contentType: "Research",
    bin: "omarchy",
    note: "Remain calm. Admire the typography. Take notes.",
    moment: "RESEARCH RABBIT HOLE +1",
  },
  {
    id: "dhh-club-constitution",
    app: "Pages",
    icon: "¶",
    text: "Article IV: No meeting may outlive a Rails deploy",
    detail: "Article V was replaced with a convention over configuration.",
    meta: "yesterday",
    tone: "rose",
    clipType: "Text",
    contentType: "Document",
    bin: "dhh",
    note: "Ratified unanimously by one extremely decisive member.",
    moment: "CLUB LAW PRESERVED",
  },
  {
    id: "toe-hair-trial",
    app: "PubMed",
    icon: "Rx",
    text: "Double-blind, sock-controlled trial of motivational whispering",
    detail: "Participants could identify the placebo sock by its lack of emotional support.",
    meta: "yesterday",
    tone: "mint",
    clipType: "Text",
    contentType: "Research",
    bin: "follicles",
    note: "Recruit larger sample. Preferably with toes.",
    moment: "CITATION NEEDED BADLY",
  },
  {
    id: "loom-button",
    app: "Finder",
    icon: "◫",
    text: "ask-me-about-LOOM-button-actually-final.png",
    detail: "A wearable invitation to receive a surprisingly long answer about LOOM.",
    meta: "yesterday",
    tone: "amber",
    clipType: "Image",
    contentType: "PNG",
    bin: "lucasarts",
    note: "Nobody asked. The button remains optimistic.",
    moment: "IMAGE TEXT EXTRACTED",
  },
  {
    id: "chuck-plant",
    app: "Notes",
    icon: "Aa",
    text: "Chuck the Plant care schedule: water never; observe suspiciously",
    detail: "The plant has survived several decades of adventure-game offices through pure narrative immunity.",
    meta: "2 days",
    tone: "mint",
    clipType: "Text",
    contentType: "Reminder",
    bin: "lucasarts",
    note: "If it moves, close the mansion and call Bernard.",
    moment: "REMINDER KEPT INERT",
  },
  {
    id: "purple-tentacle-plan",
    app: "Freeform",
    icon: "⌁",
    text: "Phase 1: Drink toxic sludge\nPhase 2: Grow arms\nPhase 3: Take on the world",
    detail: "A strategic plan praised for clarity and criticized for its sludge dependency.",
    meta: "2 days",
    tone: "violet",
    clipType: "Text",
    contentType: "Plan",
    bin: "lucasarts",
    note: "Green Tentacle has concerns about organizational culture.",
    moment: "THREE STEPS CLASSIFIED",
  },
  {
    id: "lint-field-sample",
    app: "Voice Memos",
    icon: "◉",
    text: "field-recording-pocket-left-front-07.m4a",
    detail: "Eleven minutes of fabric movement, one coin, and the distant call of a receipt.",
    meta: "3 days",
    tone: "rose",
    clipType: "File",
    contentType: "Audio",
    bin: "lint",
    note: "Transcript begins: ‘rustle rustle profound silence.’",
    moment: "TRANSCRIBED LOCALLY",
  },
  {
    id: "remember-parking",
    app: "Maps",
    icon: "⌖",
    text: "Rental car: Level P3, section C, next to a pillar that looks load-bearing",
    detail: "This information will feel unnecessary right up until it becomes the only information in the world.",
    meta: "3 days",
    tone: "blue",
    clipType: "Text",
    contentType: "Location",
    bin: "remember",
    note: "The pillar is gray. This narrows nothing down.",
    moment: "PROTECTED FROM HUBRIS",
  },
  {
    id: "remember-wifi",
    app: "Messages",
    icon: "…",
    text: "Guest Wi-Fi: NiceTryFBI_5G · password: ask-the-person-who-lives-here",
    detail: "A credential with excellent security properties and terrible automation support.",
    meta: "4 days",
    tone: "amber",
    clipType: "Text",
    contentType: "Credential-ish",
    bin: "remember",
    note: "Not a real password. Still somehow incorrect.",
    moment: "CONCEALED ON PRINCIPLE",
  },
  {
    id: "recipe-lasagna",
    app: "Paprika",
    icon: "⌘",
    text: "Lasagna for one horse (or forty nervous people)",
    detail: "Layer until the pan develops structural opinions. Bake until neigh-adjacent.",
    meta: "5 days",
    tone: "amber",
    clipType: "Text",
    contentType: "Recipe",
    bin: "recipes",
    note: "Substitute cottage cheese only after informing the horse.",
    moment: "SERVINGS BOUNDED",
  },
  {
    id: "recipe-coffee",
    app: "Notes",
    icon: "Aa",
    text: "Cold brew concentrate: coffee, water, and the patience of a lighthouse keeper",
    detail: "Steep for 18 hours or until you begin speaking exclusively in tasting notes.",
    meta: "1 wk",
    tone: "mint",
    clipType: "Text",
    contentType: "Recipe",
    bin: "recipes",
    note: "Dilution remains a personal matter.",
    moment: "RECIPE NORMALIZED",
  },
  {
    id: "vollebak-full-metal",
    app: "Safari",
    icon: "↗",
    text: "Vollebak Full Metal Jacket — 11km of copper, seven pockets, zero subtlety",
    detail: "A weatherproof jacket with enough copper to make airport security begin writing a memoir.",
    meta: "1 wk",
    tone: "amber",
    clipType: "Text",
    contentType: "Product",
    bin: "vollebak",
    note: "Business case: become a beautifully articulated Faraday cage.",
    moment: "MATERIAL SCIENCE DETECTED",
  },
  {
    id: "vollebak-mars",
    app: "Notes",
    icon: "Aa",
    text: "Packing list for Mars: copper jacket, abyss hoodie, one normal sock",
    detail: "The normal sock is the most speculative technology on the list.",
    meta: "1 wk",
    tone: "rose",
    clipType: "Text",
    contentType: "Checklist",
    bin: "vollebak",
    note: "Do not let the toe-hair study recruit the sock.",
    moment: "APOCALYPSE OUTFIT PINNED",
  },
  {
    id: "metroid-morph-ball",
    app: "Freeform",
    icon: "◉",
    text: "Morph Ball ergonomics review: still unclear where Samus puts her knees",
    detail: "The Chozo standards committee has closed the issue as ‘works in production.’",
    meta: "2 wk",
    tone: "violet",
    clipType: "Text",
    contentType: "Research",
    bin: "metroid",
    note: "Do not search for anatomical diagrams during lunch.",
    moment: "CHOZO TECHNOLOGY INSPECTED",
  },
  {
    id: "metroid-door",
    app: "Xcode",
    icon: "{ }",
    text: "if (door.color === missileColor) door.open(); else beepJudgmentally();",
    detail: "A complete access-control system based on shooting the correct color of door.",
    meta: "2 wk",
    tone: "mint",
    clipType: "Text",
    contentType: "Code",
    bin: "metroid",
    note: "Security review requests fewer missiles in authentication flow.",
    moment: "MISSILE DOOR CLASSIFIED",
  },
  {
    id: "wordpress-hook",
    app: "PhpStorm",
    icon: "<?",
    text: "add_filter( 'the_content', 'please_stop_filtering_the_content', 999 );",
    detail: "Priority 999: arriving late enough to see what everyone else did to the paragraph.",
    meta: "3 wk",
    tone: "blue",
    clipType: "Text",
    contentType: "Code",
    bin: "wordpress",
    note: "Works unless another plugin has stronger feelings at priority 1000.",
    moment: "HOOK PRIORITY ESCALATED",
  },
  {
    id: "buddypress-avatar",
    app: "Safari",
    icon: "↗",
    text: "BuddyPress avatar crop modal: a 14-year diplomatic history",
    detail: "Every circle begins as a square with a complicated past.",
    meta: "3 wk",
    tone: "amber",
    clipType: "Text",
    contentType: "Issue",
    bin: "wordpress",
    note: "Regression only occurs when the user has a face.",
    moment: "LEGACY CONTEXT RECOVERED",
  },
  {
    id: "bbpress-forum",
    app: "Terminal",
    icon: ">_",
    text: "wp bbpress repair all-the-things --please --dry-run",
    detail: "A command that is spiritually valid and technically unavailable.",
    meta: "3 wk",
    tone: "mint",
    clipType: "Text",
    contentType: "Command",
    bin: "wordpress",
    note: "The forum freshness cache remembers 2014 with alarming clarity.",
    moment: "FORUM RECOUNT QUEUED",
  },
  {
    id: "technics-55",
    app: "Safari",
    icon: "↗",
    text: "Technics SL-1200 55th Anniversary Edition — gold details, serialized temptation",
    detail: "Limited to 12,000 units worldwide, which is exactly 11,999 too many opportunities for restraint to fail.",
    meta: "1 mo",
    tone: "amber",
    clipType: "Text",
    contentType: "Product",
    bin: "technics",
    note: "Need is a strong word. Direct-drive cultural continuity is better.",
    moment: "PURCHASE JUSTIFICATION SAVED",
  },
  {
    id: "technics-cue",
    app: "Music",
    icon: "♪",
    text: "Cue lever lowered with the solemnity of a lunar landing",
    detail: "The record contains three chords. The ceremony contains multitudes.",
    meta: "1 mo",
    tone: "violet",
    clipType: "Text",
    contentType: "Observation",
    bin: "technics",
    note: "Stylus force calibrated; emotional force remains unbounded.",
    moment: "WOW AND FLUTTER MINIMIZED",
  },
  {
    id: "dott-stamp",
    app: "ScummVM",
    icon: "☠",
    text: "A contract, a stamp collection, and several preventable changes to history",
    detail: "Day of the Tentacle remains the leading authority on time travel through office supplies.",
    meta: "1 mo",
    tone: "rose",
    clipType: "Text",
    contentType: "Plan",
    bin: "lucasarts",
    note: "Ask Hoagie whether the Constitution has a watermark.",
    moment: "TIMELINE REVISION SAVED",
  },
  {
    id: "factorio-spaghetti",
    app: "Factorio",
    icon: "⚙",
    text: "Temporary iron belt workaround — do not inspect after hour 40",
    detail: "The workaround now supplies six sciences and has acquired constitutional protections.",
    meta: "2 mo",
    tone: "amber",
    clipType: "Text",
    contentType: "Plan",
    bin: "factorio",
    note: "Main bus advocates are not welcome in this save file.",
    moment: "SPAGHETTI PROTECTED",
  },
  {
    id: "factorio-inserter",
    app: "Numbers",
    icon: "ƒx",
    text: "Inserter throughput calculation accidentally becomes evening plans",
    detail: "One more belt balance, then bed. The factory has heard this before.",
    meta: "2 mo",
    tone: "mint",
    clipType: "Text",
    contentType: "Research",
    bin: "factorio",
    note: "Copper cable expansion approved without environmental review.",
    moment: "THROUGHPUT OPTIMIZED 0.4%",
  },
  {
    id: "factorio-biter",
    app: "Messages",
    icon: "…",
    text: "The biters object to the factory on procedural grounds",
    detail: "Pollution was entered into evidence. Artillery entered shortly afterward.",
    meta: "2 mo",
    tone: "rose",
    clipType: "Text",
    contentType: "Dispute",
    bin: "factorio",
    note: "Mediation ended when the flamethrower turret joined the call.",
    moment: "STAKEHOLDER FEEDBACK ARCHIVED",
  },
];

const archiveSubjects = [
  ["Guybrush Threepwood’s LinkedIn endorsements", "lucasarts"],
  ["Bernard Bernoulli’s emergency mansion checklist", "lucasarts"],
  ["Purple Tentacle’s completely normal five-year plan", "lucasarts"],
  ["Chuck the Plant’s unauthorized memoir", "lucasarts"],
  ["Hoagie’s founding-father road trip itinerary", "lucasarts"],
  ["Laverne’s tentacle-era medical license renewal", "lucasarts"],
  ["the SCUMM Bar employee handbook", "lucasarts"],
  ["Stan’s previously owned ship warranty", "lucasarts"],
  ["Murray the demonic skull’s motivational newsletter", "lucasarts"],
  ["Samus Aran’s Morph Ball ergonomic complaint", "metroid"],
  ["a Chozo statue waiting to hand out the Long Beam", "metroid"],
  ["Ridley’s recurring calendar invite titled ‘final battle’", "metroid"],
  ["a Metroid save room’s ambient-sound performance review", "metroid"],
  ["the baby Metroid’s extremely complicated adoption papers", "metroid"],
  ["a blue missile door’s zero-trust security manifesto", "metroid"],
  ["the DHH fan club’s Nürburgring seating chart", "dhh"],
  ["an Omarchy theme ranked entirely by snack compatibility", "omarchy"],
  ["a Framework screwdriver with its own Substack", "commerce"],
  ["Vollebak’s 11-kilometre copper-jacket packing slip", "vollebak"],
  ["a Full Metal Jacket explaining itself to airport security", "vollebak"],
  ["the Apocalypse Jacket’s suspiciously calm weather forecast", "vollebak"],
  ["a ceramic T-shirt with a more impressive résumé than mine", "vollebak"],
  ["the Technics SL-1200 anniversary serial-number horoscope", "technics"],
  ["a cue lever lowering with ceremonial precision", "technics"],
  ["a record brush’s strongly held opinion about fingerprints", "technics"],
  ["the direct-drive motor’s request for one song without scrutiny", "technics"],
  ["WordPress core’s seventeen-year-old compatibility promise", "wordpress"],
  ["a plugin conflict involving three innocent shortcodes", "wordpress"],
  ["BuddyPress activity streams discussing their feelings", "wordpress"],
  ["bbPress freshness metadata refusing to acknowledge time", "wordpress"],
  ["the_content filter after everyone has filtered the content", "wordpress"],
  ["WP-Cron arriving whenever traffic feels emotionally available", "wordpress"],
  ["a Factorio main bus annexing the living room", "factorio"],
  ["four inserters debating optimal copper-cable throughput", "factorio"],
  ["the factory’s one final expansion before bed", "factorio"],
  ["a biter submitting formal comments on industrial zoning", "factorio"],
  ["a belt-balancer diagram discovered at hour sixty-three", "factorio"],
  ["the Kovarex process’s patient onboarding document", "factorio"],
  ["the left pocket’s lint census", "lint"],
  ["the right pocket’s strongly worded rebuttal", "lint"],
  ["a toe follicle seeking Series A funding", "follicles"],
  ["the three-headed monkey witness statement", "lucasarts"],
  ["Edna’s mansion microwave inspection report", "lucasarts"],
  ["a rubber chicken pulley procurement request", "lucasarts"],
  ["the horse-mask quarterly business review", "commerce"],
  ["a tiny hand worn on a slightly larger tiny hand", "commerce"],
  ["the cold brew that became self-aware at hour nineteen", "recipes"],
  ["the rental car hiding behind the load-bearing pillar", "remember"],
  ["a Rails monolith insisting it is just well integrated", "dhh"],
  ["the year of the Linux desktop’s revised calendar invite", "omarchy"],
  ["a dairy farmer’s insult-swordfighting performance review", "lucasarts"],
  ["the pocket ethics board’s sealed findings", "lint"],
] as const;

const archiveArtifacts = [
  "final-final-USE-THIS-ONE.md",
  "meeting-notes-no-one-admits-writing.txt",
  "screenshot-with-the-important-part-cropped-out.png",
  "research-tab-37-of-92.url",
  "receipt-for-a-business-essential-probably.pdf",
  "untitled-thesis-recovered-6.pages",
  "command-that-worked-once.sh",
  "credentials-but-in-a-funny-way.txt",
  "diagram-of-the-obvious-v12.excalidraw",
  "voice-memo-from-inside-a-pocket.m4a",
  "shopping-list-with-lore.md",
  "extremely-actionable-action-items.rtf",
  "fan-club-constitution-redline.docx",
  "pirate-career-ladder.csv",
  "toe-hair-observations-anonymized.xlsx",
  "omarchy-rice-rice-baby.conf",
  "mansion-floorplan-minus-secret-lab.pdf",
  "ask-me-about-loom-print-ready.svg",
  "horse-mask-roi-calculator.numbers",
  "lint-sample-chain-of-custody.json",
  "morph-ball-knee-clearance-study.pdf",
  "zebes-door-color-access-matrix.csv",
  "chozo-artifact-return-policy.txt",
  "full-metal-jacket-airport-script.md",
  "apocalypse-wardrobe-layering-diagram.svg",
  "sl1200-anniversary-restraint-budget.xlsx",
  "stylus-force-emotional-force-comparison.numbers",
  "wordpress-hook-priority-peace-treaty.php",
  "buddypress-avatar-crop-postmortem.md",
  "bbpress-recount-everything-eventually.sh",
  "factorio-temporary-belt-permanent-save.blueprint",
  "inserter-throughput-date-night.xlsx",
  "biter-community-feedback-final.pdf",
  "tentacle-timeline-merge-conflicts.json",
  "constitution-with-novelty-stamp.docx",
  "hamster-microwave-risk-register.csv",
] as const;

const archiveConsequences = [
  "Pinned because confidence briefly exceeded judgment.",
  "Protected from retention and several peer reviewers.",
  "Copied twice, understood never.",
  "Filed under ‘circle back when the moon is right.’",
  "OCR detected the phrase ‘this seems promising’ 41 times.",
  "The Smart Bin matched and immediately requested counsel.",
  "Added to Queue between courage and consequences.",
  "Revision 12 restores the typo everyone secretly preferred.",
  "The classifier returned ‘Document, technically.’",
  "Saved for Thursday, a day with no further specification.",
  "Marked important by the same person who named the file.",
  "Local analysis found structure but declined to find meaning.",
  "A WordPress hook fired; no witnesses agree on the priority.",
  "The factory grew while this sentence was being classified.",
  "Samus could retrieve it, provided she has the correct beam.",
  "Copper content exceeds both expectations and luggage allowance.",
  "Playback remains direct-drive; the purchase rationale does not.",
  "The timeline was altered, but the note survived in revisions.",
  "BuddyPress marked it active three minutes into the future.",
  "A long-handed inserter has moved this into the wrong Bin.",
] as const;

const archiveNotesByBin: Record<string, readonly string[]> = {
  commerce: ["Cross-reference with the banana phone incident.", "Keep until the return window or dignity expires."],
  omarchy: ["Read after changing the theme for the sixth time.", "The year of the Linux desktop has accepted this calendar invite."],
  dhh: ["Convention over configuration overthinking.", "Fan club minutes must fit inside one Rails deploy."],
  lint: ["The pocket ethics board requests another fiber sample.", "Denim remains the primary habitat under study."],
  follicles: ["The toe-hair control group remains extremely smooth.", "Peer review requested a larger sock-controlled trial."],
  lucasarts: ["If found, return to the SCUMM Bar lost-and-found barrel.", "Purple Tentacle approved this before growing arms."],
  recipes: ["Dilution remains a personal matter.", "The horse has not approved this serving size."],
  remember: ["Future me will recognize the context instantly. Surely.", "Protected from confidence and short-term memory."],
  vollebak: ["Vollebak may already make trousers capable of solving this.", "File under wearable material science and beautiful overkill."],
  metroid: ["Ask Samus to check behind the suspiciously bombable wall.", "The Chozo standards committee marked this production-ready."],
  wordpress: ["Requires WordPress 3.7 through whatever year this currently is.", "bbPress says the topic is fresh; archaeology says otherwise."],
  technics: ["File beside the turntable receipt and the denial stage.", "The cue point is exact. The purchase rationale is evolving."],
  factorio: ["The factory can stop growing after this one tiny outpost.", "A long-handed inserter filed this note from two tiles away."],
};

const archiveApps = [
  ["Safari", "↗", "blue"],
  ["Notes", "Aa", "amber"],
  ["Terminal", ">_", "mint"],
  ["Finder", "◫", "violet"],
  ["Messages", "…", "blue"],
  ["ScummVM", "☠", "rose"],
  ["WordPress", "W", "blue"],
  ["Factorio", "⚙", "amber"],
  ["Music", "♪", "violet"],
  ["Metroid", "◉", "mint"],
] as const;

const archiveContentTypes = ["Research", "URL", "Draft", "Command", "Evidence", "Plan", "Reminder", "Document", "Blueprint", "Product", "Issue", "Audio"] as const;

const generatedArchive = Array.from({ length: demoLibraryTotal - featuredDemoClips.length }, (_, index): DemoClip => {
  const [subject, bin] = archiveSubjects[index % archiveSubjects.length];
  const artifact = archiveArtifacts[Math.floor(index / archiveSubjects.length) % archiveArtifacts.length];
  const consequence = archiveConsequences[Math.floor(index / (archiveSubjects.length * 3)) % archiveConsequences.length];
  const [app, icon, tone] = archiveApps[index % archiveApps.length];
  const serial = String(index + featuredDemoClips.length + 1).padStart(3, "0");

  return {
    id: `archive-${serial}`,
    app,
    icon,
    text: `${artifact} — ${subject}`,
    detail: consequence,
    meta: index < 60 ? `${index + 6} days` : `${Math.floor(index / 30) + 2} mo`,
    tone,
    clipType: index % 11 === 0 ? "File" : "Text",
    contentType: archiveContentTypes[index % archiveContentTypes.length],
    bin,
    note: index % 3 === 0 ? archiveNotesByBin[bin][index % archiveNotesByBin[bin].length] : undefined,
    moment: `HISTORY ITEM ${serial} · STILL WEIRD`,
  };
});

export const demoClips: DemoClip[] = [...featuredDemoClips, ...generatedArchive];
